#!/bin/bash

sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg
sudo ./openocd -f ../tcl/interface/ftdi/olimex-arm-usb-tiny-h.cfg -f  ../tcl/interface/ftdi/olimex-arm-jtag-swd.cfg -f ../tcl/target/max32660_erase.cfg







